name: Sklearn Server Docker Publisher

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - test

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: sklearnserver

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  # Use matrix to run tests for different platforms
  test:
    runs-on: ${{ matrix.platform == 'linux/s390x' && 'self-hosted' || 'ubuntu-latest' }}
    strategy:
      matrix:
        platform: [linux/s390x, linux/amd64, linux/arm64/v8]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          context: python
          file: python/sklearn.Dockerfile
          push: false
          provenance: false

  # Job for building and pushing the image for `amd64`
  build-amd64:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Export version variable
        run: |
          IMAGE_ID=quay.io/ayshamk/kserve/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [ "$VERSION" == "test" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV

      - name: Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: python
          file: python/sklearn.Dockerfile
          push: true
          tags: ${{ env.IMAGE_ID }}:amd64-${{ env.VERSION }}
          provenance: false

  # Job for building and pushing the image for `arm64`
  build-arm64:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Export version variable
        run: |
          IMAGE_ID=quay.io/ayshamk/kserve/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [ "$VERSION" == "test" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV

      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8
          context: python
          file: python/sklearn.Dockerfile
          push: true
          tags: ${{ env.IMAGE_ID }}:arm64-v8-${{ env.VERSION }}
          provenance: false

  # Job for building and pushing the image for `s390x` on self-hosted runner
  build-s390x:
    needs: test
    runs-on: self-hosted  # Change this to `self-hosted` for s390x
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Export version variable
        run: |
          IMAGE_ID=quay.io/ayshamk/kserve/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [ "$VERSION" == "test" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV

      - name: Build and push s390x image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/s390x
          context: python
          file: python/sklearn.Dockerfile
          push: true
          tags: ${{ env.IMAGE_ID }}:s390x-${{ env.VERSION }}
          provenance: false

  # Job for creating and pushing the manifest list
  push-manifest:
    needs: [build-amd64, build-arm64, build-s390x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Export version variable
        run: |
          IMAGE_ID=quay.io/ayshamk/kserve/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [ "$VERSION" == "test" ] && VERSION=latest

          echo VERSION=$VERSION >> $GITHUB_ENV
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV

      - name: Create and push the manifest
        run: |
          # Create the manifest list
          docker buildx imagetools create \
            --tag quay.io/ayshamk/kserve/sklearnserver:${{ env.VERSION }} \
            quay.io/ayshamk/kserve/sklearnserver:amd64-${{ env.VERSION }} \
            quay.io/ayshamk/kserve/sklearnserver:arm64-v8-${{ env.VERSION }} \
            quay.io/ayshamk/kserve/sklearnserver:s390x-${{ env.VERSION }}

      - name: Push the manifest list
        run: |
          docker buildx build --push \
            --tag quay.io/ayshamk/kserve/sklearnserver:${{ env.VERSION }} \
            .
